


export const ExperienceList = [
  {
    id: 1,
    type: "education",
    school_company: " Sant Tukaram Madhyamik Vidhyalay, Pune , Maharashtra ",
    date: "2015",
    degree_position: "SSC",
    work_on: "",
    percentage: 91.00,
    website: "",
  },
  {
    id: 2,
    type: "education",
    school_company: "MES Abasaheb Garware College, Pune, Maharashtra",
    date: "2015-2017",
    degree_position: "HSC",
    work_on: "Science",
    percentage: 76.00,
    website: "https://garwarecollege.mespune.in/",
  },
  {
    id: 3,
    type: "education",
    school_company: "MES Abasaheb Garware College, Pune, Maharashtra",
    date: "2017-2020",
    degree_position: "B.Sc",
    work_on: "Computer Science",
    percentage: 82.00,
    website: "https://garwarecollege.mespune.in/",
  },
  {
    id: 4,
    type: "education",
    school_company: "MES Abasaheb Garware College, Pune, Maharashtra",
    date: "2020-2022",
    degree_position: "M.Sc",
    work_on: "Computer Science",
    percentage: 80.00,
    website: "https://garwarecollege.mespune.in/",
  },
  {
    id: 5,
    type: "work",
    school_company: "Intern at FDS Infotech Ltd.  Pune , Maharashtra",
    subtitle: " Pune , Maharashtra",
    date: "October 2021 - December 2021",
    degree_position: "Intern",
    work_on: "Worked on .Net Framework",
    website: "http://fdsinfotech.com/",
  },
  {
    id: 6,
    type: "work",
    school_company: "Apprentice- Software Engineer at 3Pillar Global",
    subtitle: "Noida , India",
    date: "December 2021 - June 2022",
    degree_position: "Apprentice-Software Engineer",
    work_on: "Learned and upskilled into front-end technologies like HTML, CSS, JavaScript, React ,MUI",
    website: "https://www.3pillarglobal.com/",
  },
  {
    id: 7,
    type: "work",
    school_company: "Software Engineer at 3Pillar Global",
    subtitle: "Noida , India",
    date: "July 2022 - Present",
    degree_position: "Software Engineer",
    work_on: "Working on technbologies like ReactJS , HTML , CSS , TypeScript , AWS, Terraform",
    website: "https://www.3pillarglobal.com/",
  },
];